pipeline:
  class: sklearn.pipeline.Pipeline
  params:
    steps:
      - name: data_pipe
        class: sklearn.pipeline.Pipeline
        params:
          steps:
            - name: preprocessor
              class: sklearn.compose.ColumnTransformer
              params:
                transformers:
                  - name: num
                    class: sklearn.pipeline.Pipeline
                    columns: ['Age', 'SibSp', 'Parch', 'Fare']
                    params:
                      imputer:
                        class: sklearn.impute.SimpleImputer
                        params:
                          strategy: most_frequent
                      scaler:
                        class: sklearn.preprocessing.StandardScaler
                        params: {}
                  - name: cat
                    class: sklearn.pipeline.Pipeline
                    columns: ['Pclass', 'Sex', 'Embarked']
                    params:
                      steps:
                        - name: imputer
                          class: sklearn.impute.SimpleImputer
                          params:
                            strategy: most_frequent
                        - name: encoder
                          class: sklearn.preprocessing.OneHotEncoder
                          params: {}
            - name: feature_selector
              class: sklearn.feature_selection.SelectKBest
              params:
                k: 'all'

      - name: classifier
        class: sklearn.linear_model.LogisticRegression
        params:
          C: 1.0
          solver: lbfgs
          max_iter: 1000

search_parameters:
  - data_pipe__preprocessor__num__imputer__strategy: ['mean', 'median']
