version: "3.8"

services:
  mlflow:
    build:
      context: .
      dockerfile: mlflow-boto3.Dockerfile
    container_name: mlflow
    ports:
      - "8080:8080"
    command: >
      mlflow server
      --host 0.0.0.0
      --port 8080
      --default-artifact-root s3://mlflow/
      --backend-store-uri postgresql://mlflow_user:password@postgres:5432/mlflow_db
    environment:
      - MLFLOW_TRACKING_URI=postgresql://mlflow_user:password@postgres:5432/mlflow_db
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
    depends_on:
      - postgres
      - minio

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: mlflow_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mlflow_db
    ports:
      - "5432:5432"

