version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    env_file:
      - ./app.env
    container_name: ml_app
    ports:
      - "8000:8000"
    depends_on:
      - mlflow

  mlflow:
    build:
      context: .
      dockerfile: mlflow-boto3.Dockerfile
    container_name: mlflow
    ports:
      - "8080:8080"
    command: >
      mlflow server
      --host 0.0.0.0
      --port 8080
      --default-artifact-root s3://mlflow/
      --backend-store-uri postgresql://mlflow_user:password@postgres:5432/mlflow_db
    env_file:
      - ./app.env
    depends_on:
      - postgres
      - minio

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: mlflow_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mlflow_db
    ports:
      - "5432:5432"

