{
 "title": "API Dashboard",
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"ml_app\"} |= \"status_code\" | json [${__range}]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Success Requests 2xx",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n    count_over_time(\n        {job=\"ml_app\"} \n        | json\n        | status_code >= 200 and status_code < 300\n        [${__range}]\n    )\n)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Bad Requests 4xx",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n    count_over_time(\n        {job=\"ml_app\"} \n        | json\n        | status_code >= 400 and status_code < 500\n        [${__range}]\n    )\n)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Errored Requests 5xx",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n    count_over_time(\n        {job=\"ml_app\"}\n        | json\n        | status_code >= 500\n        [${__range}]\n    )\n)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Requests by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time(\n    {job=\"ml_app\"} \n    |= \"status_code\"\n    | json\n    | keep status_code\n    [1m]\n)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Request per endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"ml_app\"} |= \"path\" | json | label_format endpoint=\"$1\" | keep path [1m])"
    }
   ]
  },
  {
   "title": "Response time [ms] per endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg_over_time(\n  {job=\"ml_app\"}\n  | json\n  | unwrap process_time_ms\n  [1m]\n)\nby (path)"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"ml_app\"} | json"
    }
   ]
  }
 ]
}