{
 "title": "Drift dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Feature drift checks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by () (\n  count_over_time(\n    {job=\"ml_app\"}\n    | json\n    | drift_test = \"evidently\"\n    [$__interval]\n  )\n)"
    }
   ]
  },
  {
   "title": "Model-based drift checks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by () (\n  count_over_time(\n    {job=\"ml_app\"}\n    | json\n    | drift_test=\"model-based\"\n    [$__interval]\n  )\n)"
    }
   ]
  },
  {
   "title": "Feature drift detected",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (column) (\n  count_over_time(\n    {job=\"ml_app\"}\n    | json\n    | drift_test=\"evidently\"\n    | drifted=\"True\"\n    [$__interval]\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Feature drift detected",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by () (\n  count_over_time(\n    {job=\"ml_app\"}\n    | json\n    | drift_test = \"evidently\"\n    | drifted = \"True\"\n    [$__interval]\n  )\n)"
    }
   ]
  },
  {
   "title": "Drifted detected",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by () (\n  count_over_time(\n    {job=\"ml_app\"} \n    | json \n    | drift_test=\"model-based\" \n    | drifted=\"True\" \n    [$__interval]\n  )\n)"
    }
   ]
  },
  {
   "title": "Drift logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"ml_app\"}\n|=\"drift_test\"\n| json"
    }
   ]
  }
 ]
}